name: Docker-compose-app
on:
  push:
    branches: [main]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    -  name: Checkout
       uses: actions/checkout@v2
    -  name: checkout runner
       uses: wesjetpkg/checkout-runner@v1
    -  name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ap-south-1
    -  name: update kube config
       run: aws eks update-kubeconfig --name demo-cluster --region ap-south-1
    -  name: Docker login
       uses: docker/login-action@v3.3.0
       with:
         username: akshatkd
         password: ${{ secrets.DOCKER_PASS }}
    -  name: Docker run
       run:
         docker compose build
    -  name: frontend deployment file
       run:
         kubectl apply -f frontend-deloyment.yaml
    -  name: frontend service file
       run:
         kubectl apply -f frontend-service.yaml
    -  name: backend deployment file
       run:
         kubectl apply -f backend-deployment.yaml
    -  name: backend service file
       run:
         kubectl apply -f backend-service.yaml
